export const config = {
  GOOGLE_MAPS_API_KEY: "AIzaSyA50V6U3gro6UcBWHPwMQ35TvnmLnTN_Ak",
  MAPBOX_API_KEY: "pk.eyJ1IjoidGF0ZW5kYXp3IiwiYSI6ImNsbTdpZGt2NTAweGsza3MyODd5Z20za2UifQ.naBorxMyGM2ewbWQROY4OA"
};
